# ─────────────────────────────────────────────────────────────────────────────
# CyberPlayground — One-Command Setup Script (Windows PowerShell)
# Run:  .\setup.ps1
# ─────────────────────────────────────────────────────────────────────────────

Write-Host "`n🛡️  CyberPlayground Setup" -ForegroundColor Cyan
Write-Host "─────────────────────────────────" -ForegroundColor DarkGray

# ── Check Node.js ─────────────────────────────────────────────────────────────
try { $nodeVer = node --version } catch { Write-Host "❌ Node.js not found. Install from https://nodejs.org" -ForegroundColor Red; exit 1 }
Write-Host "✅ Node.js $nodeVer" -ForegroundColor Green

# ── Install dependencies ──────────────────────────────────────────────────────
Write-Host "`n📦 Installing dependencies..." -ForegroundColor Yellow
Set-Location server; npm install --silent; Set-Location ..
Set-Location client; npm install --silent; Set-Location ..
npm install --silent
Write-Host "✅ Dependencies installed" -ForegroundColor Green

# ── Generate secure SESSION_SECRET ────────────────────────────────────────────
$secret = node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"

# ── Create server/.env if missing ─────────────────────────────────────────────
if (-not (Test-Path "server\.env")) {
  @"
# Auto-generated by setup.ps1
DATABASE_URL=file:./dev.db
SESSION_SECRET=$secret
RAZORPAY_KEY_ID=rzp_test_xxxxxxxxxxxx
RAZORPAY_KEY_SECRET=your_razorpay_key_secret
RAZORPAY_PLAN_ID=plan_xxxxxxxxxxxx
WEBHOOK_SECRET=your_razorpay_webhook_secret
PORT=3001
NODE_ENV=development
CLIENT_URL=http://localhost:5173
"@ | Set-Content "server\.env"
  Write-Host "✅ server/.env created (SESSION_SECRET auto-generated)" -ForegroundColor Green
} else {
  Write-Host "⚠️  server/.env already exists — skipping" -ForegroundColor Yellow
}

# ── Create client/.env if missing ─────────────────────────────────────────────
if (-not (Test-Path "client\.env")) {
  @"
VITE_RAZORPAY_KEY=rzp_test_xxxxxxxxxxxx
"@ | Set-Content "client\.env"
  Write-Host "✅ client/.env created" -ForegroundColor Green
} else {
  Write-Host "⚠️  client/.env already exists — skipping" -ForegroundColor Yellow
}

# ── Apply database schema ─────────────────────────────────────────────────────
Write-Host "`n🗄️  Setting up database..." -ForegroundColor Yellow
Set-Location server
npx prisma db push --accept-data-loss 2>&1 | Out-Null
Write-Host "✅ Database schema applied" -ForegroundColor Green

# ── Seed database ─────────────────────────────────────────────────────────────
Write-Host "🌱 Seeding scenarios, badges, and daily challenges..." -ForegroundColor Yellow
npx prisma db seed 2>&1 | Out-Null
Write-Host "✅ Database seeded" -ForegroundColor Green
Set-Location ..

# ── Done ─────────────────────────────────────────────────────────────────────
Write-Host "`n✨ Setup complete!" -ForegroundColor Green
Write-Host "─────────────────────────────────" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Next: Fill in your Razorpay keys in server/.env" -ForegroundColor White
Write-Host "  Then run:  npm run dev" -ForegroundColor Cyan
Write-Host ""
Write-Host "  App  → http://localhost:5173" -ForegroundColor Green
Write-Host "  API  → http://localhost:3001/api/health" -ForegroundColor DarkGreen
Write-Host ""
